openapi: 3.0.1
info:
  title: tech blog hub site의 API
  description: 카테고리, 회사, 검색어를 기반으로 한 검색 API (페이징 지원)
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
    description: Local server
paths:
  /search:
    $ref: "./request/articleInfo.yml#/search"