openapi: 3.0.1
info:
  title: tech blog hub site의 API
  description: 카테고리, 회사, 검색어를 기반으로 한 검색 API (페이징 지원)
  version: 1.0.0
servers:
  - url: https://www.tech-blog-hub.site/api/v1
paths:
  /article-infos/search:
    $ref: "./request/articleInfo.yml#/search"
  /redirect:
    $ref: "./request/redirect.yml#/redirect"
  /recommend:
    $ref: "./request/recommend.yml#/recommend"

tags:
  - name: ArticleInfo
    description: 웹사이트 화면 구성용 api
  - name: Redirect
    description: 사용자 행동 로깅용 API
  - name: Recommend
    description: 크롬 확장 프로그램용 추천 API