http.host: 0.0.0.0
xpack.monitoring:
  elasticsearch:
    hosts:
    - ${ELASTICSEARCH_HOSTS}
    password: ${ELASTICSEARCH_PASSWORD}
    ssl:
      certificate_authority: /usr/share/logstash/config/certs/ca.crt
      verification_mode: certificate
    username: ${ELASTICSEARCH_USERNAME}
  enabled: ${XPACK_MONITORING_ENABLED}
xpack.monitoring.enabled: true
