openapi: 3.0.1
info:
  title: tech blog hub site의 API
  description: 카테고리, 회사, 검색어를 기반으로 한 검색 API (페이징 지원)
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
    description: Local server
paths:
  /search:
    get:
      operationId: getPosts
      summary: 검색 수행
      description: 카테고리, 회사, 검색어를 기반으로 검색을 수행합니다. 페이징을 지원합니다.
      parameters:
        - in: query
          name: hashtags
          schema:
            type: array
            items:
              type: string
          style: form
          explode: false
          description: 검색할 카테고리 목록 (선택사항, 쉼표로 구분)
        - in: query
          name: company
          schema:
            type: string
          description: 검색할 회사 이름 (선택사항)
        - in: query
          name: query
          schema:
            type: string
          description: 검색어 (선택사항)
        - in: query
          name: page
          schema:
            type: integer
            minimum: 0
            default: 0
          description: 페이지 번호 (0부터 시작, 기본값 0)
        - in: query
          name: size
          schema:
            type: integer
            minimum: 1
            maximum: 30
            default: 20
          description: 페이지 당 결과 수 (기본값 20, 최대 30)
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseDto'
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseDto'
components:
  schemas:
    ResponseDto:
      type: object
      description: API response format
      required:
        - status
        - message
        - content
      properties:
        status:
          type: integer
        message:
          type: string
        content:
          $ref: '#/components/schemas/SearchResult'

    SearchResult:
      type: object
      nullable: true
      required:
        - posts
        - page
      properties:
        posts:
          type: array
          items:
            $ref: '#/components/schemas/Post'
        page:
          $ref: '#/components/schemas/Page'

    Post:
      type: object
      required:
        - title
        - pubDate
        - companyName
        - url
        - summarizedText
        - hashtags
      properties:
        title:
          type: string
        pubDate:
          type: string
        companyName:
          type: string
        url:
          type: string
        summarizedText:
          type: string
        hashtags:
          type: array
          items:
            type: string

    Page:
      type: object
      required:
        - pageNumber
        - pageSize
        - totalElements
        - totalPages
      properties:
        pageNumber:
          type: integer
        pageSize:
          type: integer
        totalElements:
          type: integer
        totalPages:
          type: integer