services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: elasticsearch
    environment:
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ../elasticsearch-data:/usr/share/elasticsearch/data
      - ./certs:/usr/share/elasticsearch/config/certs
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - elastic
    command: >
      /bin/bash -c "
        elasticsearch-plugin install --batch analysis-nori;
        /usr/local/bin/docker-entrypoint.sh elasticsearch
      "
    healthcheck:
      test: ["CMD-SHELL", "curl -s --cacert /usr/share/elasticsearch/config/certs/elasticsearch.crt -u ${ELASTICSEARCH_USERNAME}:${ELASTIC_PASSWORD} https://${DNS_NAME}:9200 -o /dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  setup_elasticsearch:
    image: curlimages/curl:latest
    depends_on:
      elasticsearch:
        condition: service_healthy
    command: >
      sh -c '
        curl -k --cacert /certs/elasticsearch.crt -u ${ELASTICSEARCH_USERNAME}:${ELASTIC_PASSWORD} -X PUT "https://${DNS_NAME}:9200/article_infos?pretty" -H "Content-Type: application/json" -d "{
          \"settings\": {
            \"analysis\": {
              \"analyzer\": {
                \"nori_analyzer\": {
                  \"type\": \"custom\",
                  \"tokenizer\": \"nori_tokenizer\",
                  \"filter\": [
                    \"nori_readingform\",
                    \"nori_number\",
                    \"trim\",
                    \"my_stop\"
                  ]
                }
              },
              \"tokenizer\": {
                \"nori_tokenizer\": {
                  \"type\": \"nori_tokenizer\",
                  \"decompound_mode\": \"mixed\"
                }
              },
              \"filter\": {
                \"my_stop\": {
                  \"type\": \"stop\",
                  \"stopwords\": [\"_korean_\", \"은\", \"는\", \"이\", \"가\"]
                }
              }
            }
          },
          \"mappings\":{
            \"properties\":{
              \"id\":{\"type\":\"keyword\"},
              \"title\":{\"type\":\"text\", \"analyzer\": \"nori_analyzer\"},
              \"pub_date\":{\"type\":\"date\"},
              \"company_name\":{\"type\":\"keyword\"},
              \"url\":{\"type\":\"keyword\"},
              \"summarized_text\":{\"type\":\"text\", \"analyzer\": \"nori_analyzer\"},
              \"hashtags\":{
                \"type\":\"text\",
                \"analyzer\":\"standard\",
                \"fields\": {
                  \"keyword\": {
                    \"type\": \"keyword\",
                    \"ignore_above\": 256
                  }
                }
              },
              \"created_at\":{\"type\":\"date\"}
            }
          }
        }"
      '
    volumes:
      - ./certs:/certs
    networks:
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash:8.7.1
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./certs:/usr/share/logstash/config/certs
    ports:
      - 5044:5044
    environment:
      ELASTICSEARCH_HOSTS: "https://${DNS_NAME}:9200"
      ELASTICSEARCH_USERNAME: "${ELASTICSEARCH_USERNAME}"
      ELASTICSEARCH_PASSWORD: "${ELASTIC_PASSWORD}"
      XPACK_MONITORING_ENABLED: "true"
    networks:
      - elastic
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9600"]
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - KIBANA_HOST=0.0.0.0  
      - ELASTICSEARCH_HOSTS=https://${DNS_NAME}:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./certs:/usr/share/kibana/config/certs
    networks:
      - elastic
    depends_on:
      elasticsearch:
        condition: service_healthy

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.7.1
    user: root  # Run as root to have permission to change file modes
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./filebeat/crawler-filebeat.yml:/usr/share/filebeat/crawler-filebeat.yml
      - ./filebeat/spring-backend-filebeat.yml:/usr/share/filebeat/spring-backend-filebeat.yml      
      - ../crawler/log:/var/log/crawler:ro
      - ../backend/log:/var/log/spring-backend:ro
      - ./certs:/usr/share/filebeat/certs:ro
    command: >
      /bin/bash -c "
      chmod go-w /usr/share/filebeat/filebeat.yml &&
      chmod go-w /usr/share/filebeat/crawler-filebeat.yml &&
      chmod go-w /usr/share/filebeat/spring-backend-filebeat.yml &&
      filebeat -e -c /usr/share/filebeat/filebeat.yml
      "
    depends_on:
      logstash:
        condition: service_healthy
    networks:
      - elastic
    
networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch-data:
    driver: local
