services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: elasticsearch
    environment:
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ../elasticsearch-data:/usr/share/elasticsearch/data
      - ./certs:/usr/share/elasticsearch/config/certs
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - elastic
    healthcheck:
      test: ["CMD-SHELL", "curl -s --cacert /usr/share/elasticsearch/config/certs/elasticsearch.crt -u ${ELASTICSEARCH_USERNAME}:${ELASTIC_PASSWORD} https://${DNS_NAME}:9200 -o /dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  setup_elasticsearch:
    image: curlimages/curl:latest
    depends_on:
      elasticsearch:
        condition: service_healthy
    command: >
      sh -c '
        curl -k --cacert /certs/elasticsearch.crt -u ${ELASTICSEARCH_USERNAME}:${ELASTIC_PASSWORD} -X PUT "https://${DNS_NAME}:9200/article_infos?pretty" -H "Content-Type: application/json" -d "{\"mappings\":{\"properties\":{\"id\":{\"type\":\"keyword\"},\"title\":{\"type\":\"text\"},\"pub_date\":{\"type\":\"date\"},\"company_name\":{\"type\":\"keyword\"},\"url\":{\"type\":\"keyword\"},\"content\":{\"type\":\"text\"},\"summarized_text\":{\"type\":\"text\"},\"hashtags\":{\"type\":\"keyword\"},\"created_at\":{\"type\":\"date\"}}}}"
      '
    volumes:
      - ./certs:/certs
    networks:
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash:8.7.1
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./certs:/usr/share/logstash/config/certs
    ports:
      - 5044:5044
    environment:
      ELASTICSEARCH_HOSTS: "https://${DNS_NAME}:9200"
      ELASTICSEARCH_USERNAME: "${ELASTICSEARCH_USERNAME}"
      ELASTICSEARCH_PASSWORD: "${ELASTIC_PASSWORD}"
      XPACK_MONITORING_ENABLED: "true"
    networks:
      - elastic
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9600"]
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - KIBANA_HOST=0.0.0.0  
      - ELASTICSEARCH_HOSTS=https://${DNS_NAME}:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./certs:/usr/share/kibana/config/certs
    networks:
      - elastic
    depends_on:
      elasticsearch:
        condition: service_healthy

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.7.1
    user: root  # Run as root to have permission to change file modes
    volumes:
      - ./filebeat/:/usr/share/filebeat/
      - ../crawler/log:/var/log/crawler:ro
      - ../backend/log:/var/log/spring-backend:ro
      - ./certs:/usr/share/filebeat/certs:ro
    command: >
      /bin/bash -c "
      chmod go-w /usr/share/filebeat/filebeat.yml &&
      chmod go-w /usr/share/filebeat/crawler-filebeat.yml &&
      chmod go-w /usr/share/filebeat/spring-backend-filebeat.yml &&
      filebeat -e -c /usr/share/filebeat/filebeat.yml
      "
    depends_on:
      logstash:
        condition: service_healthy
    networks:
      - elastic
    
networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch-data:
    driver: local
