- type: log
  id: crawler-logs
  enabled: true
  paths:
    - /var/log/crawler/*.log
  fields:
    application: crawler
  include_lines: 
    - '"msg":"Update Done"'
    - '"level":"ERROR"'
    - '"level":"WARN"'
  harvester_limit: 0
  scan_frequency: 10s
  tail_files: true